//-------------------------------------------
// This file was autogenerated by GUI Builder
//-------------------------------------------

#include "./lib_digini.h"
#ifdef DIGINI_USE_GRAFX

//-------------------------------------------

extern const FontInfo_t FONT_InfoTable[NUMBER_OF_FONT];
extern const uint8_t FONT_RawData[29242];

//-------------------------------------------

#endif // DIGINI_USE_GRAFX
