//-------------------------------------------
// This file was autogenerated by GUI_Builder
//-------------------------------------------

#include <stdint.h>
#include "digini_cfg.h"
#ifdef DIGINI_USE_GRAFX
#include "lib_grafx.h"
#include "lib_compression.h"

const uint32_t Progress_bar[18] =
{
    0xFFACB1B3, 0xFF657276, 0xFF6F7D82, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 
    0xFF728186, 0xFFB3B9BB, 
};


extern const StaticImageInfo_t SII_Progress_bar;
const StaticImageInfo_t SII_Progress_bar =
{
    18,
    18,
    4,
    32,
    (uint8_t*)Progress_bar,
    18,
    ARGB8888,
    COMPX_COMPRESSION_NONE,
};

//-------------------------------------------------------------------------------------------------

#endif // DIGINI_USE_GRAFX
