//-------------------------------------------
// This file was autogenerated by GUI Builder
//-------------------------------------------

#include "./lib_digini.h"
#ifdef DIGINI_USE_GRAFX

//-------------------------------------------

enum FONT_ListID_t
{
    FONT_AMIRI_12_R,
    FONT_ARIAL_12_B,
    FONT_DS-DIGITAL_16_B,
    NUMBER_OF_FONT
}

//-------------------------------------------

extern const FontInfo_t* FONT_pInfoTable[NUMBER_OF_FONT];
extern const uint8_t FONT_RawData[67420];

//-------------------------------------------

#endif // DIGINI_USE_GRAFX
