//-------------------------------------------
// This file was autogenerated by GUI_Builder
//-------------------------------------------

#include "./lib_digini.h"
#ifdef DIGINI_USE_GRAFX

//-------------------------------------------

const uint32_t ProgressBar[18] =
{
    0xFFACB1B3, 0xFF657276, 0xFF6F7D82, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186, 0xFF728186,
    0xFF728186, 0xFFB3B9BB,
};


extern const StaticImageInfo_t SII_ProgressBar;
const StaticImageInfo_t SII_ProgressBar =
{
    18,
    18,
    4,
    32,
    (uint8_t*)ProgressBar,
    18,
    PIXEL_FORMAT_ARGB8888,
    COMPX_COMPRESSION_NONE,
};

//-------------------------------------------------------------------------------------------------

#endif // DIGINI_USE_GRAFX
